### ISSUE TITLE
.cspec issue

### ISSUE THREAD

**Issue by esaulenka** [astrelsky/RL78_sleigh#2]
Looks like modern Ghidra have more strict rules for compiler specification XML.

Actual 11.3.dev (haven't checked with the previous) cannot load this module
```
Open failed: ghidra.program.model.lang.CompilerSpecNotFoundException: Exception reading rl78:LE:16:default/default(rl78.cspec:43): parameter list entries must be ordered by storage class

```

As a workaround, it can be simply fixed by removing `metatype` attribute:
```
--- a/data/languages/rl78.cspec
+++ b/data/languages/rl78.cspec
@@ -37,7 +37,7 @@
       <pentry minsize="1" maxsize="2">
         <register name="BC0"/>
       </pentry>
-      <pentry minsize="3" maxsize="3" metatype="ptr">
+      <pentry minsize="3" maxsize="3">
         <addr space="join" piece1="C0" piece2="AX0"/>
       </pentry>
       <pentry minsize="4" maxsize="4">
```

PS one more question regarding this topic. This calling convention called 'v2_call'. Do you have any thoughts about v1 ? Perhaps 'my' binary was made by some compiler that doesn't compatible with this v2_call.

**Comment by ikuyas** [comment]
I faced the same problem and when I came here, I found a solution and tried it. I edited the file, and was able to compile as follows. 
`support/sleigh Ghidra/Processors/RL78_sleigh/data/languages/rl78.slaspec`
but when I start Ghidra and try to disassemble it, I get the following error. Please let me know if you know how to solve this problem.

```
Invalid Class specified for customDisassemblerClass (ghidra.rl78.disassembly.RL78Disassembler): rl78:LE:16:default
java.lang.RuntimeException: Invalid Class specified for customDisassemblerClass (ghidra.rl78.disassembly.RL78Disassembler): rl78:LE:16:default
	at ghidra.program.disassemble.Disassembler.getLanguageSpecificDisassembler(Disassembler.java:1824)
	at ghidra.program.disassemble.Disassembler.getDisassembler(Disassembler.java:140)
	at ghidra.app.cmd.disassemble.DisassembleCommand.doDisassembly(DisassembleCommand.java:187)
	at ghidra.app.cmd.disassemble.DisassembleCommand.applyTo(DisassembleCommand.java:156)
	at ghidra.app.cmd.disassemble.DisassembleCommand.applyTo(DisassembleCommand.java:33)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:103)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:351)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: ghidra.rl78.disassembly.RL78Disassembler
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at ghidra.program.disassemble.Disassembler.getLanguageSpecificDisassembler(Disassembler.java:1810)
	... 7 more

---------------------------------------------------
Build Date: 2024-Nov-05 1643 EST
Ghidra Version: 11.2.1
Java Home: C:\Program Files\Eclipse Adoptium\jdk-21.0.3.9-hotspot
JVM Version: Eclipse Adoptium 21.0.3
OS: Windows 10 10.0 amd64
```

**Comment by esaulenka** [comment]
@ikuyas perhaps Andrew will explain better, but most likepy you compiled java-part in some inproper way.
This module includes small [java part](https://github.com/astrelsky/RL78_sleigh/blob/master/src/main/java/ghidra/rl78/disassembly/RL78Disassembler.java)  and you should compile it with gradle.
Don't know what exactly you did wrong, probably you compiled it againt wrong Ghidra version or just forgot to copy results.

Anyway, you issue is not related to .cspec file.
